insert into categoria values(1,"CARROCERIAS");
insert into categoria values(2,"SEMIRREMOLQUES");
insert into categoria values(3,"VOLTEOS");
insert into categoria values(4,"AUTOTANQUES");
insert into categoria values(5,"REMOLQUES");
insert into categoria values(6,"EQUIPOS ESPECIALES");
insert into categoria values(7,"ESTRUCTURAS");
insert into categoria values(8,"INVERNADEROS");
insert into categoria values(9,"PLANTAS INDUSTRIALES");
insert into categoria values(10,"EQUIPO INDUSTRIAL Y COMERCIAL");

insert into producto values(1,1,'CAJA SECA','Para diferentes productos. Herramienta, productos alimenticios, plásticos, muebles, etc. Capacidad: 14.4 m³');
insert into producto values(2,1,'CAJA DE REFIRGERACION','Diseñado para productos que requieran conservación, refrigeración, congelación o simplemente un clima controlado como: (mariscos, pescado, abarrotes, frutas, verduras, medicamentos y químicos) Capacidad: 14.4 m³');
insert into producto values(3,1,'CAJA DE REDILLAS','Para el uso de carga de diferentes productos: herramienta, productos alimenticios, plásticos, muebles, etc. Capacidad: 5.1 m³');
insert into producto values(4,1,'CARROCERIA JAULA','Para el transporte de diferentes materiales como: electrodomésticos, plásticos, mueblería, línea blanca, etc. Capacidad: 7 m3 ');
insert into producto values(5,1,'CARROCERIA CERRADA','Para el transporte de diferentes materiales como: electrodomésticos, plásticos, mueblería, línea blanca, etc. Capacidad: 7 m3 ');
insert into producto values(6,2,'CAJA SECA','Para el uso de carga de diferentes productos: herramienta, productos alimenticios, plásticos, muebles, etc. Capacidad máxima: 32 y/o 37 toneladas');
insert into producto values(7,2,'CAJA DE REFRIGERACION','Para el transporte de carga que requiera, conservación, refrigeración, congelación o simplemente un clima controlado como: (mariscos, pescado, abarrotes, frutas, verduras, medicamentos y químicos) Capacidad máxima: 32 y/o 37 toneladas ');
insert into producto values(8,2,'CAJA JAULA','Fabricadas para transporte de acero, material de construcción, ganado, frutas y verduras. Nos adaptamos a las necesidades de cada cliente. Capacidad máxima: 32 y/o 37 toneladas');
insert into producto values(9,2,'PLATAFORMAS','Para carga de material de construcción, industrial, ganadero, etc. Capacidad máxima: 32 y/o 37 toneladas. ');
insert into producto values(10,2,'DOLLY','Para remolcar camioneta o camión Capacidad máxima: 32 Toneladas');
insert into producto values(11,2,'GONDOLAS','Para la carga de materiales como: construcción, plásticos, industrial, alimenticio, acero, etc. Capacidades: 24, 30 y 36 toneladas');
insert into producto values(12,3,'VOLTEOS','Para transportar material de construcción, basura, tierra, minería, chatarra, agrícola, etc. Capacidades: 3, 6, 7 y 14 m³');
insert into producto values(13,4,'AUTOTANQUE SOBRE CAMION','Destinado para el transporte de líquidos, gases licuados o sólidos en suspensión. Capacidad máxima: 20,000, 25,000, y 30,000 lts. ');
insert into producto values(14,4,'AUTOTANQUE SOBRE REMOLQUE','Destinado para el transporte de líquidos, gases licuados o sólidos en suspensión. Capacidad máxima: 20,000, 25,000, y 30,000 lts. ');
insert into producto values(15,4,'AUTOTANQUE INOXIDABLE','Destinado para el transporte de líquidos, gases licuados o sólidos en suspensión. Capacidad máxima: 20,000, 25,000, y 30,000 lts. ');
insert into producto values(16,5,'REMOLQUE','Para uso múltiple según el uso que se requiera Capacidad máxima: 32 y/o 72 toneladas');
insert into producto values(17,5,'REMOLQUE COCINA','Para uso múltiple según el uso que se requiera Capacidad máxima: 32 y/o 72 toneladas');
insert into producto values(18,5,'REMOLQUE DE ACERO INOXIDABLE','Para uso múltiple según el uso que se requiera Capacidad máxima: 32 y/o 72 toneladas');
insert into producto values(19,6,'TOLVAS','Para el transporte de diferentes productos alimenticios. Capacidad máxima: 20 Toneladas.');
insert into producto values(20,6,'SEMIRREMOLQUE LOW BOY/ CAMA BAJA','Para carga de diferente maquinaria pesada ');
insert into producto values(21,6,'PLANTA DE ASFALTO','Capacidad mínima: 12 camiones de volteo de 7m3 en turnos de 8 horas para un total de 84m3. Capacidad máxima: 13.7 camiones de volteo de 7m3 en turnos de 8 horas para un total de 95.9m3 Dimensiones: LARGO: 7.5mts ANCHO: 2.5mts ALTO: 3.1mts PESO: 2.5ton Colocación: Opción 1: Colocación en un camión torton o rabón. Opción 2: Colocación en un remolque pequeño.');
insert into producto values(22,7,'GRADAS','Estructura: Fabricados en lámina de acero al carbón en diferentes espesores. Tornillos de anclaje Placas de conexiones Placas de base para columna Juntas o conexiones Columnas de monten, Montenes Lamina acanalada');
insert into producto values(23,7,'ESTRUCTURAS','Fabricación de estructuras según requerimientos del cliente');
insert into producto values(24,8,'INVERNADEROS','Para crear un clima óptimo para el crecimiento de plantas, especias, frutas, Etc.  nos ajustamos al diseño y necesidad del cliente. Todos cumpliendo con las especificaciones de Norma (NOM) básicas de SCT y sin problema para cumplir con especificaciones especiales, propias o normas de Organismos Nacionales e Internacionales. Se fabrican en cualquier capacidad y diseño que se requiera.');
insert into producto values(25,9,'TOLVA ','Capacidad: De acuerdo a la necesidad y requerimientos del cliente, según capacidad y producto.');
insert into producto values(26,9,'PLANTA DE ALIMENTOS','Fabricación de plantas de alimentos según requerimientos del cliente');
insert into producto values(27,10,'ANTENA','Fabricación de antenas según requerimientos del cliente');
insert into producto values(28,10,'POSTES','Fabricación de postes según requerimientos del cliente');
insert into producto values(29,10,'SEÑALAMIENTOS','Fabricación de señalamientos según requerimientos del cliente');
insert into producto values(30,10,'PLACAS PARA SEÑALAMIENTO','Fabricación de placas para todo tipo de señalamiento según requerimientos del cliente');
insert into producto values(31,10,'CANALETAS','Fabricación de canaletas según requerimientos del cliente');
insert into producto values(32,10,'NIDOS','Fabricación de nidos según requerimientos del cliente');
insert into producto values(33,10,'ESTANTERIAS',' Fabricación de estanterias según requerimientos del cliente');
insert into producto values(34,10,'ESPECIALES','Fabricación de equipo especial');
insert into producto values(35,10,'CHIMENEAS ',' Fabricación de chimeneas de lamina');
insert into producto values(36,10,'CENICEROS','Fabricación de ceniceros');
insert into producto values(37,10,'BASURERO','Fabricación de botes de basura ');
insert into producto values(38,10,'CHAROLAS DE DESECHOS',' Fabricación de charolas de desechos según requerimientos del cliente');



insert into imagen values(1,13,'autotanque_sobre_camion1.png');
insert into imagen values(2,13,'autotanque_sobre_camion2.png');
insert into imagen values(3,13,'autotanque_sobre_camion3.png');
insert into imagen values(4,13,'autotanque_sobre_camion4.png');
insert into imagen values(5,13,'autotanque_sobre_camion5.png');
insert into imagen values(6,13,'autotanque_sobre_camion6.png');
insert into imagen values(7,15,'autotanque_sobre_inoxidable1.png');
insert into imagen values(8,15,'autotanque_sobre_inoxidable2.png');
insert into imagen values(9,15,'autotanque_sobre_inoxidable3.png');
insert into imagen values(10,14,'autotanque_sobre_remolque1.png');
insert into imagen values(11,14,'autotanque_sobre_remolque2.png');
insert into imagen values(12,14,'autotanque_sobre_remolque3.png');
insert into imagen values(13,14,'autotanque_sobre_remolque4.png');
insert into imagen values(14,14,'autotanque_sobre_remolque5.png');
insert into imagen values(15,3,'carroceria_caja_redillas1.png');
insert into imagen values(16,3,'carroceria_caja_redillas2.png');
insert into imagen values(17,2,'carroceria_caja_refrigeracion1.png');
insert into imagen values(18,2,'carroceria_caja_refrigeracion2.png');
insert into imagen values(19,2,'carroceria_caja_refrigeracion3.png');
insert into imagen values(20,1,'carroceria_caja_seca1.png');
insert into imagen values(21,1,'carroceria_caja_seca2.png');
insert into imagen values(22,1,'carroceria_caja_seca3.png');
insert into imagen values(23,1,'carroceria_caja_seca4.png');
insert into imagen values(24,5,'carroceria_cerrada1.png');
insert into imagen values(25,5,'carroceria_cerrada2.png');
insert into imagen values(26,5,'carroceria_cerrada3.png');
insert into imagen values(27,4,'carroceria_jaula1.png');
insert into imagen values(28,4,'carroceria_jaula2.png');
insert into imagen values(29,4,'carroceria_jaula3.png');
insert into imagen values(30,4,'carroceria_jaula4.png');
insert into imagen values(31,27,'equipo_antena1.png');
insert into imagen values(32,37,'equipo_basurero1.png');
insert into imagen values(33,31,'equipo_canaleta1.png');
insert into imagen values(34,36,'equipo_cenicero1.png');
insert into imagen values(35,36,'equipo_cenicero2.png');
insert into imagen values(36,36,'equipo_cenicero3.png');
insert into imagen values(37,38,'equipo_charola_desecho1.png');
insert into imagen values(38,38,'equipo_charola_desecho2.png');
insert into imagen values(39,38,'equipo_charola_desecho3.png');
insert into imagen values(40,35,'equipo_chimenea.png');
insert into imagen values(41,34,'equipo_especial1.png');
insert into imagen values(42,34,'equipo_especial2.png');
insert into imagen values(43,21,'equipo_especial_planta_asfalto1.png');
insert into imagen values(44,21,'equipo_especial_planta_asfalto2.png');
insert into imagen values(45,21,'equipo_especial_planta_asfalto3.png');
insert into imagen values(46,21,'equipo_especial_planta_asfalto4.png');
insert into imagen values(47,21,'equipo_especial_planta_asfalto5.png');
insert into imagen values(48,21,'equipo_especial_planta_asfalto6.png');
insert into imagen values(49,20,'equipo_especial_semiremolque_lowboy1.png');
insert into imagen values(50,20,'equipo_especial_semiremolque_lowboy2.png');
insert into imagen values(51,20,'equipo_especial_semiremolque_lowboy3.png');
insert into imagen values(52,19,'equipo_especial_tolva1.png');
insert into imagen values(53,19,'equipo_especial_tolva2.png');
insert into imagen values(54,19,'equipo_especial_tolva3.png');
insert into imagen values(55,19,'equipo_especial_tolva4.png');
insert into imagen values(56,19,'equipo_especial_tolva5.png');
insert into imagen values(57,19,'equipo_especial_tolva6.png');
insert into imagen values(58,19,'equipo_especial_tolva7.png');
insert into imagen values(59,19,'equipo_especial_tolva8.png');
insert into imagen values(60,33,'equipo_estanteria1.png');
insert into imagen values(61,33,'equipo_estanteria2.png');
insert into imagen values(62,32,'equipo_nido1.png');
insert into imagen values(63,32,'equipo_nido2.png');
insert into imagen values(64,30,'equipo_placa_señalamiento1.png');
insert into imagen values(65,30,'equipo_placa_señalamiento2.png');
insert into imagen values(66,30,'equipo_placa_señalamiento3.png');
insert into imagen values(67,28,'equipo_poste1.png');
insert into imagen values(68,28,'equipo_poste2.png');
insert into imagen values(69,28,'equipo_poste3.png');
insert into imagen values(70,28,'equipo_poste4.png');
insert into imagen values(71,29,'equipo_señalamiento1.png');
insert into imagen values(72,29,'equipo_señalamiento2.png');
insert into imagen values(73,23,'estructura01.png');
insert into imagen values(74,23,'estructura02.png');
insert into imagen values(75,23,'estructura03.png');
insert into imagen values(76,23,'estructura04.png');
insert into imagen values(77,23,'estructura05.png');
insert into imagen values(78,23,'estructura06.png');
insert into imagen values(79,22,'estructura_gradas1.png');
insert into imagen values(80,22,'estructura_gradas2.png');
insert into imagen values(81,22,'estructura_gradas3.png');
insert into imagen values(82,24,'invernaderos1.png');
insert into imagen values(83,24,'invernaderos2.png');
insert into imagen values(84,24,'invernaderos3.png');
insert into imagen values(85,24,'invernaderos4.png');
insert into imagen values(86,24,'invernaderos5.png');
insert into imagen values(87,24,'invernaderos6.png');
insert into imagen values(88,24,'invernaderos7.png');
insert into imagen values(89,26,'planta_industrial_alimentos01.png');
insert into imagen values(90,26,'planta_industrial_alimentos02.png');
insert into imagen values(91,26,'planta_industrial_alimentos03.png');
insert into imagen values(92,26,'planta_industrial_alimentos04.png');
insert into imagen values(93,26,'planta_industrial_alimentos05.png');
insert into imagen values(94,26,'planta_industrial_alimentos06.png');
insert into imagen values(95,26,'planta_industrial_alimentos07.png');
insert into imagen values(96,26,'planta_industrial_alimentos08.png');
insert into imagen values(97,26,'planta_industrial_alimentos09.png');
insert into imagen values(98,26,'planta_industrial_alimentos10.png');
insert into imagen values(99,26,'planta_industrial_alimentos11.png');
insert into imagen values(100,26,'planta_industrial_alimentos12.png');
insert into imagen values(101,26,'planta_industrial_alimentos13.png');
insert into imagen values(102,25,'planta_industrial_tolva1.png');
insert into imagen values(103,25,'planta_industrial_tolva2.png');
insert into imagen values(104,25,'planta_industrial_tolva3.png');
insert into imagen values(105,16,'remolque01.png');
insert into imagen values(106,16,'remolque02.png');
insert into imagen values(107,16,'remolque03.png');
insert into imagen values(108,16,'remolque04.png');
insert into imagen values(109,16,'remolque05.png');
insert into imagen values(110,16,'remolque06.png');
insert into imagen values(111,16,'remolque07.png');
insert into imagen values(112,16,'remolque08.png');
insert into imagen values(113,16,'remolque09.png');
insert into imagen values(114,16,'remolque10.png');
insert into imagen values(115,16,'remolque11.png');
insert into imagen values(116,16,'remolque12.png');
insert into imagen values(117,16,'remolque13.png');
insert into imagen values(118,16,'remolque14.png');
insert into imagen values(119,18,'remolque_acero_inoxidable1.png');
insert into imagen values(120,18,'remolque_acero_inoxidable2.png');
insert into imagen values(121,18,'remolque_acero_inoxidable3.png');
insert into imagen values(122,17,'remolque_cocina1.png');
insert into imagen values(123,17,'remolque_cocina2.png');
insert into imagen values(124,17,'remolque_cocina3.png');
insert into imagen values(125,8,'semiremolque_caja_jaula1.png');
insert into imagen values(126,8,'semiremolque_caja_jaula2.png');
insert into imagen values(127,8,'semiremolque_caja_jaula3.png');
insert into imagen values(128,7,'semiremolque_caja_refrigeracion1.png');
insert into imagen values(129,6,'semiremolque_caja_seca1.png');
insert into imagen values(130,6,'semiremolque_caja_seca2.png');
insert into imagen values(131,6,'semiremolque_caja_seca3.png');
insert into imagen values(132,10,'semiremolque_dolly1.png');
insert into imagen values(133,11,'semiremolque_gondola1.png');
insert into imagen values(134,11,'semiremolque_gondola2.png');
insert into imagen values(135,11,'semiremolque_gondola3.png');
insert into imagen values(136,11,'semiremolque_gondola4.png');
insert into imagen values(137,11,'semiremolque_gondola5.png');
insert into imagen values(138,11,'semiremolque_gondola6.png');
insert into imagen values(139,11,'semiremolque_gondola7.png');
insert into imagen values(140,11,'semiremolque_gondola8.png');
insert into imagen values(141,9,'semiremolque_plataforma1.png');
insert into imagen values(142,9,'semiremolque_plataforma2.png');
insert into imagen values(143,9,'semiremolque_plataforma3.png');
insert into imagen values(144,9,'semiremolque_plataforma4.png');
insert into imagen values(145,12,'volteo1.png');
insert into imagen values(146,12,'volteo2.png');
insert into imagen values(147,12,'volteo3.png');
insert into imagen values(148,12,'volteo4.png');
insert into imagen values(149,12,'volteo5.png');
insert into imagen values(150,12,'volteo6.png');
insert into imagen values(151,12,'volteo7.png');
insert into imagen values(152,12,'volteo8.png');
